### ISSUE TITLE
Restarting rack server

### ISSUE THREAD

**Issue by cha55son** [square/rack-servlet#15]
How easy or difficult would it be to restart a rack application within a running Java process?

I currently use rails that is booted via the rack servlet and would like to quickly restart the server by sending the java process a signal (ctrl+c/d). Any advice would be greatly appreciated!

Snippet of how the rack application is created:

``` java
Path rackup = "/path/to/config.ru"; // Rails rackup file.
String rackupContent = new String(Files.readAllBytes(rackup), StandardCharsets.UTF_8);
ruby.put("rackup_script", rackupContent);
...
StringBuilder scriptBuilder = new StringBuilder().append("")
                                                 .append("Dir.chdir(apps_path);")
                                                 .append("require 'rack';")
                                                 .append("require 'jruby';")
                                                 .append("require 'java';")
                                                 .append("context = JRuby.runtime.getCurrentContext();")
                                                 .append("Rack::Builder.new_from_string(rackup_script)");
IRubyObject application = ruby.parse(script).run();
return new RackServlet(new JRubyRackApplication(application));
```

**Comment by matthewtodd** [comment]
Interesting!

Just to help me get my bearings, since you're asking about restarting, and since I assume Rails' development-mode reloading works just fine under rack servlet (does it?), is this for production?

My first thought is that, if you can handle the memory overhead, it might be easiest / safest / least fiddly to fire up a new JRuby runtime with the reloaded application, then switch it in to the running rack servlet. (Probably writing your own implementation of `com.squareup.rack.RackApplication` to handle the cutover; I have no idea how this would interact with in-flight / queued requests, though you may not need to care if this is just for your development purposes.)

**Comment by cha55son** [comment]
This would be for development only, on a development box but we will want to run rails in both dev and production mode for thorough testing, etc. In dev mode, reloading of existing classes works properly. Although there are certain things in rails that require restarts, new classes/files, certain types of route changes, etc.

Java has advantages that we want to leverage in production, but in development we want the quick restarts that are common with CRuby. This technique of restarting the server within a running java process could be a step closer to that fast boot-up time.

This probably isn't even a feature request, more like a request for a demo on how to restart the rack servlet. I'm assuming it could be useful for others in the same situation. I can try to find some time to toy around with this idea, and see if I can come up with a working example. Although, i'm not a java guy so if this seems trivial to you, feel free to paste a snippet. :)

**Comment by cha55son** [comment]
Closing this as it's best handled outside of the rack-servlet.
